# Permalinks
permalink:        pretty

# Setup
title:            Uptown Func
tagline:
description:      "I'm Michael Warnes. Software engineer"
url:              https://mawarnes.github.io
baseurl:          /

future:           false

author:
  name:           'Micahel Warnes'
  url:

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
version:

github:           https://github.com/mawarnes
devto:            https://dev.to/mawarnes
linkedin:         https://linkedin.com/in/mawarnes

plugins:
  - jekyll-paginate
  - jekyll-gist

sidebar_blog_link:  '/blog'
